# Generated by Django 3.1.1 on 2020-11-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='MovieName')),
                ('director', models.CharField(max_length=100, verbose_name='Director')),
                ('description', models.TextField(verbose_name='Descrtiptions')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('added_date', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
